version: "3"
services:
  reservaos:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 7000:7000
    environment:
      ENV: development
  db:
    image: postgres:13
    ports:
      - 6000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
